[sonic_platform/sfp_base] Add common definition for get SFP error status
Azure/sonic-platform-common pull request #194
Opened 2021-06-08 15:13 UTC by stephenxs

#### Description

Add common definitions for getting SFP error status

- Platform API definition: `get_sfp_status`
- Related constant definitions

Signed-off-by: Stephen Sun <stephens@nvidia.com>

#### Motivation and Context

#### How Has This Been Tested?

#### Additional Information (Optional)

2021-06-11 16:29 UTC, jleveque requested changes

2021-06-11 16:29 UTC, jleveque commented on sonic_platform_base/sfp_base.py
> +    SFP_ERROR_DESCRIPTION_BAD_EEPROM                = 'Bad or unsupported eeprom'
s/eeprom/EEPROM/

2021-06-14 13:39 UTC, stephenxs commented on sonic_platform_base/sfp_base.py
> +    SFP_ERROR_DESCRIPTION_BAD_EEPROM                = 'Bad or unsupported eeprom'
Fixed.

2021-06-14 16:41 UTC, jleveque approved these changes

2021-06-14 16:41 UTC, jleveque commented
/azp run

2021-06-15 01:51 UTC, stephenxs commented
Looks like it failed due to an unsatisfied dependency on yang module
```
2021-06-14T17:16:15.4207828Z WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
2021-06-14T17:16:15.4660349Z + sudo pip3 install sonic_config_engine-1.0-py3-none-any.whl
2021-06-14T17:16:15.8202969Z Processing ./sonic_config_engine-1.0-py3-none-any.whl
2021-06-14T17:16:15.8991885Z ERROR: Could not find a version that satisfies the requirement sonic-yang-mgmt>=1.0 (from sonic-config-engine) (from versions: none)
2021-06-14T17:16:15.8992828Z ERROR: No matching distribution found for sonic-yang-mgmt>=1.0
```

2021-06-15 02:06 UTC, jleveque commented
> Looks like it failed due to an unsatisfied dependency on yang module
> 
> ```
> 2021-06-14T17:16:15.4207828Z WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
> 2021-06-14T17:16:15.4660349Z + sudo pip3 install sonic_config_engine-1.0-py3-none-any.whl
> 2021-06-14T17:16:15.8202969Z Processing ./sonic_config_engine-1.0-py3-none-any.whl
> 2021-06-14T17:16:15.8991885Z ERROR: Could not find a version that satisfies the requirement sonic-yang-mgmt>=1.0 (from sonic-config-engine) (from versions: none)
> 2021-06-14T17:16:15.8992828Z ERROR: No matching distribution found for sonic-yang-mgmt>=1.0
> ```

It appears this is a new dependency which broke the CI. I have opened a PR here in an attempt to fix: https://github.com/Azure/sonic-platform-common/pull/198

2021-06-16 04:38 UTC, jleveque commented
/azp run

2021-06-16 16:25 UTC, merged