Add y-cable driver for simulated mux
Azure/sonic-platform-common pull request #213
Opened 2021-08-19 13:50 UTC by wangxin

#### Description

This PR added y-cable driver for simulated mux. This y-cable driver conforms with the requirement of https://github.com/Azure/SONiC/pull/757/files

#### Motivation and Context

After the abstract y-cable base class is added for multi-vendor y-cable support, we also need a y-cable driver for simulated mux used in lab testing.

#### How Has This Been Tested?

This change is still under test. It will be tested on testbeds using simulated mux.

#### Additional Information (Optional)

2021-08-20 01:03 UTC, vdahiya12 requested changes

2021-08-20 03:27 UTC, wangxin commented on sonic_y_cable/microsoft/y_cable_simulated.py
> +        YCableBase.__init__(self, port, logger)
Yes

2021-08-20 04:42 UTC, vdahiya12 commented on sonic_y_cable/microsoft/y_cable_simulated.py
> +            mux_simulator = json.load(open(self.UX_SIMULATOR_CONFIG_FILE))
typo UX_SIMULATOR_CONFIG_FILE should be MUX_SIMULATOR_CONFIG_FILE

2021-08-20 10:45 UTC, wangxin commented
Python lib `requests` is not available in the pmon docker. Need to update the code to use `urllib`.

2021-08-25 04:15 UTC, vdahiya12 approved these changes

2021-08-25 06:00 UTC, merged