[sfp-refactor] Add initial support for SFF-8636 in sonic_xcvr
Azure/sonic-platform-common pull request #218
Opened 2021-09-20 20:39 UTC by andywongarista

#### Description

This PR adds basic support for the SFF-8636 transceiver spec within the new sonic_xcvr package.
Also adds additional helper functions in XcvrApi that check if a particular xcvr feature is supported.

#### Motivation and Context

See the HLD: https://github.com/Azure/SONiC/blob/master/doc/sfp-refactor/sfp-refactor.md

#### How Has This Been Tested?

Added new unit test under tests/sonic_xcvr
Verified API calls on an Arista platform

#### Additional Information (Optional)

2021-10-06 13:13 UTC, prgeor requested changes
could you address review comments?

2021-10-06 16:37 UTC, andywongarista commented on sonic_platform_base/sonic_xcvr/api/xcvr_api.py
> +    def get_lpmode_support(self):
Not all modules support low power mode: https://github.com/Azure/sonic-mgmt/blob/e4e42ec8028bf51b39587e2b53e526d505fe7938/tests/platform_tests/api/test_sfp.py#L178

2021-10-06 16:38 UTC, andywongarista commented on sonic_platform_base/sonic_xcvr/api/public/sff8636.py
> +    def get_lpmode_support(self):
See other response

2021-10-07 05:32 UTC, prgeor approved these changes

2021-10-07 05:46 UTC, merged