Implement Low Power mode support in CMIS devices.
Azure/sonic-platform-common pull request #232
Opened 2021-11-08 10:20 UTC by aravindmani-1

#### Description
Add LP mode support for CMIS devices.

#### Motivation and Context
Low Power mode can be set in CMIS devices by reading/writing in EEPROM.

#### How Has This Been Tested?
Tested in DellEMC Z9332f platform.
[CMIS lpmode.txt](https://github.com/Azure/sonic-platform-common/files/7496110/CMIS.lpmode.txt)

#### Additional Information (Optional)

2021-11-16 11:40 UTC, prgeor requested changes

2021-11-16 11:40 UTC, prgeor commented on sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
> +        self.SET_LP_MODE = NumberRegField(consts.SET_LP_MODE_FIELD, self.getaddr(0x0, 26), size=1, ro=False)
can you reuse TRANS_CONFIG field?

2021-11-16 11:40 UTC, prgeor commented on sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
> +        self.MODULE_STATE = NumberRegField(consts.MODULE_STATE_FIELD, self.getaddr(0x0, 3), size=1)
can you reuse TRANS_MODULE_STATUS field?

2021-11-16 12:10 UTC, prgeor commented on sonic_platform_base/sonic_xcvr/api/public/cmis.py
> +    def set_lpmode(self, lpmode):
can you remove set_low_power()

2021-11-16 13:42 UTC, prgeor requested changes

2021-11-16 13:42 UTC, prgeor commented on sonic_platform_base/sonic_xcvr/api/public/cmis.py
> +        lpmode_val = lpmode << 4
This is affecting other bits. This should affect only bit 4 LowPwrRequestSW

2021-11-16 13:42 UTC, prgeor commented on sonic_platform_base/sonic_xcvr/fields/consts.py
>  POWER_SET_FIELD = "Power Set"
can you remove changes in this file?

2021-11-16 13:42 UTC, prgeor commented on sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
can you remove changes in this file

2021-11-22 06:14 UTC, closed without merging

2021-11-22 06:14 UTC, aravindmani-1 commented
Will open a new PR to fix this issue.

2021-11-22 06:20 UTC, aravindmani-1 commented
https://github.com/Azure/sonic-platform-common/pull/237 will fix this issue.